import {
    KeyboardArrowDown as KeyboardArrowDownIcon,
    KeyboardArrowUp as KeyboardArrowUpIcon,
    QrCode as QrCodeIcon,
    Refresh as RefreshIcon,
    Add as AddIcon,
    Help as HelpIcon,
    KeyboardArrowUp as UpdateIcon,
    Cloud as CloudIcon,
    CloudOff as CloudOffIcon,
    ArrowUpward as ArrowUpwardIcon,
    ArrowDownward as ArrowDownwardIcon,
    Remove as RemoveIcon,
    GitHub as GitHubIcon,
    MonetizationOn,
    Close as CloseIcon,
    Link as LinkIcon,
    Publish as PublishIcon,
    DeleteForever as DeleteForeverIcon,
    Delete as DeleteIcon,
    AddToPhotos as AddToPhotosIcon,
    Build as BuildIcon,
    Edit as EditIcon,
    DomainDisabled as FactoryResetIcon,
    LeakAdd as LeakAddIcon,
    SignalWifiConnectedNoInternet4 as IconNoConnection,
    SignalCellularOff as IconNotAlive,
    ContentCopy as ContentCopyIcon,
    QuestionMark as QuestionMarkIcon,
    SettingsInputAntenna as SettingsInputAntennaIcon,
    SignalWifiStatusbarNull as SignalWifiStatusbarNullIcon,
    Wifi as WifiIcon,
    WifiOff as WifiOffIcon,
    DeviceHub as DeviceHubIcon,
    AutoMode as AutoModeIcon,
    FormatListBulleted as FormatListBulletedIcon,
    UnfoldLess as UnfoldLessIcon,
    UnfoldMore as UnfoldMoreIcon
} from '@mui/icons-material';

export const icons = {
    refresh: RefreshIcon,
    add: AddIcon,
    help: HelpIcon,
    update: UpdateIcon,
    build: BuildIcon,
    addToPhotos: AddToPhotosIcon,
    deleteForever: DeleteForeverIcon,
    publish: PublishIcon,
    link: LinkIcon,
    close: CloseIcon,
    monetizationOn: MonetizationOn,
    gitHub: GitHubIcon,
    cloud: CloudIcon,
    cloudOff: CloudOffIcon,
    arrowUpward: ArrowUpwardIcon,
    arrowDownward: ArrowDownwardIcon,
    remove: RemoveIcon,
    qrCode: QrCodeIcon,
    delete: DeleteIcon,
    edit: EditIcon,
    factoryReset: FactoryResetIcon,
    chevronDown: KeyboardArrowDownIcon,
    chevronUp: KeyboardArrowUpIcon,
    leakAdd: LeakAddIcon,
    noConnection: IconNoConnection,
    notAlive: IconNotAlive,
    contentCopy: ContentCopyIcon,
    questionMark: QuestionMarkIcon,
    settingsInputAntenna: SettingsInputAntennaIcon,
    signalWifiStatusbarNull: SignalWifiStatusbarNullIcon,
    wifi: WifiIcon,
    wifiOff: WifiOffIcon,
    deviceHub: DeviceHubIcon,
    autoMode: AutoModeIcon,
    formatListBulleted: FormatListBulletedIcon,
    unfoldLess: UnfoldLessIcon,
    unfoldMore: UnfoldMoreIcon
} as const;
