name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: NPM install
        run: npm ci

      - name: Eslint
        run: npm run lint

      - name: Build
        run: npm run build